cache:
  paths:
  - node_modules/

stages:
- deploy
- production

deploy_develop:
  image: docker:latest
  stage: deploy
  tags:
    - mpt-dev
  script:
    - ./deploy-dev.sh
  only:
    - develop

deploy_production:
  image: docker:latest
  stage: production
  tags:
    - mpt-dev
  script:
    - ./deploy-prod.sh
  only:
    - production
