services:
  
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin@123
    command: server --console-address ":9001" /data

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: huyminh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - prod-postgres:/var/lib/postgresql/data

  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.docker
    command: npm run prod
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  prod-postgres: