#Build main image
#command:   docker build -t nest-api:production . --file Dockerfile.prod
#push:   docker push nest-api:production .

FROM node:16-alpine
WORKDIR /home/node/app
RUN chown -R node:node /home/node/app
USER node
COPY --chown=node:node ./ /home/node/app
RUN npm i
EXPOSE 3000
CMD ["npm", "run", "start:prod"]