
type Post {
 id: ID!
 title: String!
 content: String
 published: Boolean
 authorId: Int!
 author: User

}

input PostInputCreate {
 title: String!
 content: String
 published: Boolean
 authorId: Int!

}

input PostInputUpdate {
 title: String
 content: String
 published: Boolean
 authorId: Int

}

input PostSortInput {
 id: SortType
 title: SortType
 content: SortType
 published: SortType
 authorId: SortType

}

input PostWhereInput{
 AND: JSON
 OR: JSON
 NOT: JSON
 id: JSON
 title: JSON
 content: JSON
 published: JSON
 authorId: JSON

}

type PostList {
  entities: [Post!]
  total: Int
}

type Query {
  postById(id: ID!): Post
  posts(page: Int! = 1, limit: Int! = 25, where:PostWhereInput,  orderBy: [PostSortInput] ): PostList
}

type Mutation {
  createPost(data: PostInputCreate!): Post
  updatePost(id: ID!, data: PostInputUpdate!): Post
  deletePost(id: ID!): Post
}
