
type User {
 id: ID!
 email: String!
 password: String
 fullname: String
 meta: JSON
 posts: [Post]
 portfolios: [Portfolio]

}

input UserInput {
 email: String!
 password: String
 fullname: String
 meta: JSON

}

input UserSortInput {
 id: SortType
 email: SortType
 password: SortType
 fullname: SortType

}

input UserWhereInput{
 AND: JSON
 OR: JSON
 NOT: JSON
 id: JSON
 email: JSON
 password: JSON
 fullname: JSON

}

type UserList {
  entities: [User!]
  total: Int
}

type Query {
  userById(id: ID!): User
  users(page: Int! = 1, limit: Int! = 25, where:UserWhereInput,  orderBy: [UserSortInput] ): UserList
}

type Mutation {
  createUser(data: UserInput!): User
  updateUser(id: ID!, data: UserInput!): User
  deleteUser(id: ID!): User
}


type Mutation {
  demo: User
}


